### ISSUE TITLE
wired error

### ISSUE THREAD

**Issue by theTigerDuck** [pstaender/silverstripe-redis-cache#10]
when I try to install it on my live server. I got an Error like this:
```
[User Warning] None of the following templates could be found: Array ( [0] => StartPage [1] => Array ( [type] => Includes [0] => ...

Line 204 in /home/vcap/app/vendor/silverstripe/framework/src/View/SSViewer.php
```

On my local docker it works.

**Comment by elliot-sawyer** [comment]
Hi @theTigerDuck , thanks for raising an issue. There's no info here to indicate Redis is causing an issue or what steps we can take to reproduce it? With the information you've provided I'm not sure how we can help.

**Comment by theTigerDuck** [comment]
Well thanks for the intend. Is it compatible with Silverstripe 5.2 at all? I don't understand that flysystem part:
League\Flysystem\Cached\Storage\Memory.public:
    class: League\Flysystem\Cached\Storage\Predis
In my code I cant't find a Class with that namespace. In League\Flysystem there is no Cached folder. What am I missing here?
Is it compatible with silverstripe-s3 at all?
How do I use this Modul for storing my Sessions in Redis so far it works without the modul:
```
---
SilverStripe\Control\Session:
  cookie_secure: true
---
SilverStripe\Core\Injector\Injector:
  RedisClient:
    class: Redis
    calls:
      - [ connect, ['MYHOST',
        PORT,
        60,
        null,
        0,
        0,
        stream:
          verify_peer: true
          verify_peer_name: true
          auth:
            - MYAUTH
      ]
      ]
  Psr\SimpleCache\CacheInterface.cache:
    class: Symfony\Component\Cache\Adapter\RedisAdapter
    constructor:
      - '`REDIS_URL`'
```

**Comment by elliot-sawyer** [comment]
Definitely is compatible with 5.2, I have it running on a production server now.  I can't speak for that particular module because I don't use it. 

I can say your RedisClient config looks a bit strange, here's one I'm using now on a local docker install that closely mimics production:

```yml
---
Name: silverstripe-redis-cache
After:
  - '#corecache'
  - '#assetscache'
  - '*'
Only:
  envvarset: REDIS_URL
---
SilverStripe\Core\Injector\Injector:
  RedisClient:
    class: Predis\Client
    constructor:
      0: '`REDIS_URL`'
  RedisCacheFactory:
    class: Zeitpulse\RedisCacheFactory
    constructor:
      client: '%$RedisClient'
  SilverStripe\Core\Cache\CacheFactory: '%$RedisCacheFactory'

#You then need to configure each cache to use RedisCacheFactory:
  # vendor/silverstripe/assets/_config/assetscache.yml
  Psr\SimpleCache\CacheInterface.InterventionBackend_Manipulations:
    factory: RedisCacheFactory
  Psr\SimpleCache\CacheInterface.FileShortcodeProvider:
    factory: RedisCacheFactory
  Psr\SimpleCache\CacheInterface.ImageShortcodeProvider:
    factory: RedisCacheFactory
...
```

In your .env or CI/CD variables, you'd have this: `REDIS_URL="redis"`

I suspect that `After: '*'` rule might solve many of your issues as it did with mine.
