### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by theTigerDuck** [pstaender/silverstripe-redis-cache#11]
I have a REDIS_URL like rediss://PASSWORD@HOST:PORT but it's not working.
In my php ini session.save_path is tls://HOST:PORT?auth=PASSWORD but as REDIS_URL it's also not working.

**Comment by theTigerDuck** [comment]
It's working:
```

      parameters:
        scheme: 'tls'
        host: 'my-host.cloud'
        port: 12345
        password: 'abcd'
```
